In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import datetime as dt
import os
import numpy as np
import tensorflow as tf 
from sklearn.preprocessing import MinMaxScaler

df=pd.read_csv(r'C:\Users\HP\Documents\Courses\Handong God University\Master Thesis materials\My_Thesis_Codes\Testing\JPM_TestDataset.csv')
df2=pd.read_csv(r'C:\Users\HP\Documents\Courses\Handong God University\Master Thesis materials\My_Thesis_Codes\Testing\SMSN.IL_TestDataset.csv')
to_Be_Scaled1=df.iloc[:,1:5]
scaler=MinMaxScaler(feature_range=(0,1))
scaled_training_dataset1=scaler.fit_transform(to_Be_Scaled1)
print("JPM training set")
print(scaled_training_dataset1)
print ("\n")
to_Be_Scaled2=df2.iloc[:,1:5]
scaler2=MinMaxScaler(feature_range=(0,1))
scaled_training_dataset2=scaler2.fit_transform(to_Be_Scaled2)
print("SMSN.IL training set")
print(scaled_training_dataset2)

#

#scaled_training_dataset1.head()
#scaled_training_dataset2.head()
#plt.figure(figsize = (16,10))
#plt.plot(range(scaled_training_dataset1.shape[0]),(scaled_training_dataset1.shape[3]), label='JPM',color='orange')
#plt.plot(range(scaled_training_dataset2.shape[0]),(scaled_training_dataset2['Close']), label='SMSN.IL',color='green')
#plt.xticks(range(0,scaled_training_dataset1.shape[0],500),scaled_training_dataset1['Date'].loc[::500],rotation=45)
#plt.xticks(range(0,scaled_training_dataset2.shape[0],500),scaled_training_dataset2['Date'].loc[::500],rotation=45)
#plt.xlabel('Date',fontsize=18)
#plt.ylabel('Mid Price',fontsize=18)

#plt.legend()
#plt.show()

JPM training set
[[0.05478352 0.07631586 0.1146398  0.14708125]
 [0.10262004 0.08704458 0.11386518 0.12418928]
 [0.05279865 0.05546568 0.09430666 0.11999239]
 ...
 [0.         0.         0.0449264  0.03929792]
 [0.00952751 0.00182194 0.04337718 0.07592513]
 [0.0142914  0.00101221 0.         0.        ]]


SMSN.IL training set
[[0.70846595 0.7121116  0.74539716 0.69708492]
 [0.8204965  0.81864299 0.8432404  0.78580482]
 [0.81158498 0.81357007 0.85165702 0.80101394]
 ...
 [0.00954806 0.00253646 0.18306155 0.00253485]
 [0.         0.         0.18095739 0.        ]
 [0.07829408 0.07102093 0.23882167 0.06147022]]
